[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=[
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    # "@chainlink=lib/chainlink",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
